const videoAvila = [
    {
        id: 1,
        order: 1,
        title: "Evento Skin Club",
        videoUrl: "https://player.vimeo.com/video/1142276376",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2025",
    },
    {
        id: 2,
        order: 2,
        title: "Patch Secativos",
        videoUrl: "https://www.youtube.com/embed/pcITYA10sNk",
        orientation: "vertical",
        roles: ["Captação", "Edição"],
        year: "2025",
    },
    {
        id: 3,
        order: 3,
        title: "Glow",
        videoUrl: "https://www.youtube.com/embed/fWKN6qDridI",
        orientation: "vertical",
        roles: ["Captação", "Edição"],
        year: "2025",
    },
    {
        id: 4,
        order: 4,
        title: "Pálbebras",
        videoUrl: "https://www.youtube.com/embed/zHegZYn6s6k",
        orientation: "vertical",
        roles: ["Captação", "Edição"],
        year: "2025",
    },
    {
        id: 5,
        order: 5,
        title: "Procedimentos Mharessa",
        videoUrl: "https://www.youtube.com/embed/hC2M2Znpmvs",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2025",
    },
    {
        id: 6,
        order: 6,
        title: "Papada",
        videoUrl: "https://www.youtube.com/embed/Cg3F0tIhpQI",
        orientation: "vertical",
        roles: ["Captação", "Edição"],
        year: "2025",
    },
    {
        id: 7,
        order: 7,
        title: "Depoimento Amanda Ramalho",
        videoUrl: "https://www.youtube.com/embed/csJeQD3Ggh0",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2025",
    },
    {
        id: 8,
        order: 8,
        title: "Pincéis",
        videoUrl: "https://www.youtube.com/embed/7XfQNqh85E8",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2025",
    },
    {
        id: 9,
        order: 9,
        title: "Lábios",
        videoUrl: "https://www.youtube.com/embed/l3e91jMaxgs",
        orientation: "vertical",
        roles: ["Edição", "Captação"],
        year: "2025",
    },
    {
        id: 10,
        order: 10,
        title: "Gominhas",
        videoUrl: "https://www.youtube.com/embed/FwqCCfQIJRA",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2025",
    },
    {
        id: 11,
        order: 11,
        title: "Lifting Facial",
        videoUrl: "https://www.youtube.com/embed/u5ja7em_4Y4",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2025",
    },
    {
        id: 12,
        order: 12,
        title: "Ozempic e Mounjaro",
        videoUrl: "https://www.youtube.com/embed/uGv2UOvi8_g",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2025",
    },
    {
        id: 13,
        order: 13,
        title: "Dia das Mães",
        videoUrl: "https://www.youtube.com/embed/KHoOF8Auh-I",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2025",
    },
    {
        id: 14,
        order: 14,
        title: "Secagem e Vasinhos",
        videoUrl: "https://www.youtube.com/embed/Xj0T_G0ZmKk",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2025",
    },
    {
        id: 19,
        order: -4,
        title: "Tratamentos de Verão: Consulta",
        videoUrl: "https://player.vimeo.com/video/1142233418",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2025",
    },
    {
        id: 20,
        order: -3,
        title: "Tratamento de Verão: MPT",
        videoUrl: "https://player.vimeo.com/video/1142236277",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2025",
    },
    {
        id: 21,
        order: -2,
        title: "Tratamento de Verão: Exilis",
        videoUrl: "https://player.vimeo.com/video/1142238182",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2025",
    },
    {
        id: 22,
        order: -1,
        title: "Tratamento de Verão: Coolsculpting",
        videoUrl: "https://player.vimeo.com/video/1142237696",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2025",
    },
    {
        id: 23,
        order: -10,
        title: "EELS | Clínica Avila - Evento Allergan 2026",
        videoUrl: "https://player.vimeo.com/video/1167030031",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2026",
    },
    {
        id: 24,
        order: -11,
        title: "REELS | Clínica Avila - IMCAS 2026",
        videoUrl: "https://player.vimeo.com/video/1167030822",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2026",
    },
    {
        id: 25,
        order: -12,
        title: "REELS | Clínica Avila – Exion",
        videoUrl: "https://player.vimeo.com/video/1167030469",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2026",
    },
    {
        id: 26,
        order: -13,
        title: "TREELS | Clínica Avila - Protocolo Skin Regeneration: Paris",
        videoUrl: "https://player.vimeo.com/video/1167766028",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2026",
    }
];

const videoMusic = [
    {
        id: 1015,
        order: 1,
        title: "Trapacinha Eletrônica",
        videoUrl: "https://www.youtube.com/embed/_dLxyZY9T9o",
        orientation: "horizontal",
        roles: ["Fotografia", "Design Gráfico"],
        client: "Gabriel Delaware",
        year: "2023",
    },
    {
        id: 1016,
        order: 0,
        title: "Nos Olhos da Pintura",
        videoUrl: "https://www.youtube.com/embed/-thou-se4Ro",
        orientation: "horizontal",
        roles: ["Iluminação", "Fotografia"],
        client: "A Casa Caiu",
        year: "2024",
    },
]

const videoShortFilm = [
    {
        id: 2017,
        order: 1,
        title: "Tenho Medo é dos Vivos",
        videoUrl: "https://www.youtube.com/embed/IGKclpt3sKw",
        orientation: "horizontal",
        roles: ["Iluminação"],
        client: "A Casa Caiu",
        year: "2024",
    },
    {
        id: 2018,
        order: 0,
        title: "Verde Oliva *EM BREVE*",
        videoUrl: false,
        onGoingImg: "assets/ongoing/verdeoliva.png",
        orientation: "horizontal",
        roles: ["Fotografia"],
        client: "A Casa Caiu",
        year: "2025",
    },
]

const videoSocialMedia = [
    {
        id: 3023,
        order: 1000,
        title: "Dr. André Ahmed - Cirurgia Plástica ",
        videoUrl: "https://www.youtube.com/embed/P6qXbr4evxA",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2025",
    },
    {
        id: 3024,
        order: 1001,
        title: "Dr. André Ahmed - Cirurgia Plástica 2",
        videoUrl: "https://www.youtube.com/embed/WCZDRsx_URI",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2025",
    },
    {
        id: 3027,
        order: 999,
        title: "Show Nabru | Sec Pompéia",
        videoUrl: "https://player.vimeo.com/video/1142239873",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2025",
    },
    {
        id: 3028,
        order: 4,
        title: "REELS | PauloGuimarães - PA Clinic",
        videoUrl: "https://player.vimeo.com/video/1154135175",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2025",
    },
    {
        id: 3029,
        order: 5,
        title: "REELS | PauloGuimarães - Final de Ano 1",
        videoUrl: "https://player.vimeo.com/video/1154135076",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2025",
    },
    {
        id: 3030,
        order: 6,
        title: "REELS | PauloGuimarães - Final de Ano 2",
        videoUrl: "https://player.vimeo.com/video/1154135123",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2025",
    },
    {
        id: 3031,
        order: 7,
        title: "REELS | PauloGuimarães - Assimetria das Mama",
        videoUrl: "https://player.vimeo.com/video/1154135031",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2025",
    },
    {
        id: 3032,
        order: 8,
        title: "Comercial | GuiCintra - Anatomia do Movimento I",
        videoUrl: "https://www.youtube.com/embed/zDMkAncltJA",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2025",
    },
    {
        id: 3033,
        order: 9,
        title: "Comercial | GuiCintra - Anatomia do Movimento II",
        videoUrl: "https://www.youtube.com/embed/Krnmz_W7Srs",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2025",
    },
    {
        id: 3034,
        order: 10,
        title: "Comercial | GuiCintra - Anatomia do Movimento III",
        videoUrl: "https://www.youtube.com/embed/VKyDRvIMMUs",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2025",
    },
    {
        id: 3035,
        order: 11,
        title: "Comercial | GuiCintra - Apresentação - Anatomia do Movimento IV",
        videoUrl: "https://www.youtube.com/embed/TCgFavRD2N8",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2025",
    },
    {
        id: 3036,
        order: 12,
        title: "REELS | Aptus - 3 pilares",
        videoUrl: "https://www.youtube.com/embed/6lYgnhGaA_c",
        orientation: "vertical",
        roles: ["Captação", "Edição"],
        year: "2025",
    },
    {
        id: 3037,
        order: 13,
        title: "REELS | Aptus - 2026 está chegando",
        videoUrl: "https://www.youtube.com/embed/CwhaiR477xQ",
        orientation: "vertical",
        roles: ["Captação", "Edição"],
        year: "2025",
    },
    {
        id: 3038,
        order: 14,
        title: "REELS | Aptus - Faturamento ",
        videoUrl: "https://www.youtube.com/embed/vg8hcwqiQwo",
        orientation: "vertical",
        roles: ["Captação", "Edição"],
        year: "2025",
    },
    {
        id: 3039,
        order: 15,
        title: "REELS | Aptus - Médico do Futuro",
        videoUrl: "https://www.youtube.com/embed/BZYZR1rrZy8",
        orientation: "vertical",
        roles: ["Captação", "Edição"],
        year: "2025",
    },
    {
        id: 3040,
        order: 16,
        title: "REELS | Aptus - INOVAT 2026",
        videoUrl: "https://www.youtube.com/embed/VaR9yrqsuhM",
        orientation: "vertical",
        roles: ["Captação", "Edição"],
        year: "2025",
    },
    {
        id: 3041,
        order: -1,
        title: "REELS | Clínica Andriolo",
        videoUrl: "https://www.youtube.com/embed/bSXVlQm3Kj8",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2026",
    },
    {
        id: 3042,
        order: -2,
        title: "REELS | Clínica Andriolo – Depoimento Amadeo",
        videoUrl: "https://www.youtube.com/embed/fcyJL_6bY2U",
        orientation: "vertical",
        roles: ["Edição"],
        year: "2026",
    },

];

const videoYoutube = [
    {
        id: 4025,
        order: 1,
        title: "Os Paulistinhas - PROTEJA AS PATAS DO SEU CACHORRO – EVITE DOR E DOENÇAS",
        videoUrl: "https://www.youtube.com/embed/Hd_x1vCCWRc",
        orientation: "horizontal",
        roles: ["Edição"],
        year: "2025",
    },
    {
        id: 4026,
        order: 0,
        title: "Marcelo Trincado - Quantum RF 25",
        videoUrl: "https://player.vimeo.com/video/1167223321",
        orientation: "horizontal",
        roles: ["Edição"],
        year: "2026",
    }
];

const videoDocumentary = [
    {
        id: 5026,
        order: 10000,
        title: "Fogo Urbano - Documentário",
        videoUrl: "https://www.youtube.com/embed/-9fhcg7LIkM",
        orientation: "horizontal",
        roles: ["Fotografia", "Produção"],
        year: "2025",
    }
];

export { videoSocialMedia, videoAvila, videoMusic, videoShortFilm, videoYoutube, videoDocumentary };